export const theme = {
  colors: { bg: "#EAE6DE", ink: "#111111", marker: "#E23B2E", answerBg: "#FFDD57" },
  fonts: {
    family: "Noto Sans, sans-serif",
    titleSize: 72,
    titleWeight: 800,
    shortsTitleSize: 60,
    answerSize: 56,
    detailSize: 48,
    shortsDetailSize: 52,
    headerSize: 24,
  },
  layout: { headerMargin: 56 },
  grain: { opacity: 0.06 },
  timing: { revealDurationMs: 400, detailGapMs: 300, endFadeFrames: 30 },
  marker: { boilFps: 10, strokeWidth: 7, segments: 9, wobblePx: 2.4, sagPx: 3, overshootPct: 3, drawMs: 280 },
  boil: { boilFps: 10, jitterPx: 1.4 },
  grid: { size: 40, color: "rgba(17,17,17,0.08)", dotColor: "rgba(17,17,17,0.16)", dotMinRadius: 1, dotMaxRadius: 3.2, dotChance: 0.45 },
  progress: {
    wipeFrames: 5,
    dotSize: 15,
    dotGap: 12,
    fontSize: 30,
    dotColorActive: "#111111",
    dotColorInactive: "rgba(17,17,17,0.18)",
  },
  transition: { scrollFrames: 8, scrollDistance: 60 },
  opening: { settleFrames: 12, startScale: 1.05, maxBlur: 12 },
  scramble: { durationFrames: 14, charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz#%&@" },
  tts: { voice: "en-US-AvaNeural", rate: "+0%" },
  sfx: { begin: "sfx/Tink.m4a", click: "sfx/Pop.m4a" },
  safeZone: { shorts: { w: 900, h: 1350 } },
  fps: 30,
} as const;
